local:
  server:
    host: 127.0.0.1
    port: 6080
    auth: null
    tls: null
    pipelines: server_pipelines
    logs: logs
    db: null
  supervisor:
    host: 127.0.0.1
    port: 7080
    tls: null
    workers: 5
  docker_url: tcp://127.0.0.1:2376
  editor: nvim
  ssh: {}
  registries: {}
remote:
- server: local
  host: 127.0.0.1
  port: 6080
  tls: false
